---
- name: Stop Weblogic Admin service
  become: yes
  systemd:
    name: wls_adminserver
    state: stopped
  tags:
   - stop
   
- name: Stop Weblogic NodeManager service
  become: yes
  systemd:
    name: wls_nodemanager
    state: stopped
  tags:
   - stop


- name: Unzip Latest Weblogic CPU to PATCH_TOP
  become: yes
  become_user: "{{ os_user }}"
  ansible.builtin.unarchive:
    src: "{{ setup_home }}/{{ patch_file }}"
    dest: "{{ patch_top_home }}"
    remote_src: yes


- name: Unzip Opatch File
  become: yes
  become_user: "{{ os_user }}"
  ansible.builtin.unarchive:
    src: "{{ patch_top_home }}/{{ patch_id }}/tools/opatch/generic/{{ opatch_file }}"
    dest: "{{ patch_top_home }}"
    remote_src: yes


- name: Opatch Upgrade
  become: yes
  become_user: "{{ os_user }}"
  tags: upgradeopatch
  shell: "{{ java_home }}/bin/java -jar {{ patch_top_home }}/6880880/{{ opatch_filename }} -silent oracle_home={{ oracle_home }}"
  register: opatchupgrade
  ignore_errors: true

- debug:
    msg: "OPATCHUPGRADE: {{ opatchupgrade }}"


- name: Weblogic Critical Patch Update
  tags: cpuweblogic
  become: yes
  become_user: "{{ os_user }}"
  shell: "{{ patch_top_home }}/{{ patch_id }}/tools/spbat/generic/SPBAT/spbat.sh -phase apply -oracle_home {{ oracle_home }}"
  register: weblogiccpu
  args:
    chdir: "{{ patch_top_home }}/{{ patch_id }}"
  ignore_errors: true

- debug:
    msg: "WEBLOGIC CPU: {{ weblogiccpu }}"


- name: Start Weblogic Admin service
  become: yes
  systemd:
    name: wls_adminserver
    state: started
  tags:
   - start
   
- name: Start Weblogic NodeManager service
  become: yes
  systemd:
    name: wls_nodemanager
    state: started
  tags:
   - start
